Update autograding.yml

diff --git a/.github/workflows/autograding.yml b/.github/workflows/autograding.yml
--- a/.github/workflows/autograding.yml
+++ b/.github/workflows/autograding.yml
@@ -11,4 +11,11 @@ jobs:
     - name: Build
       run: dotnet build
     - name: Test
-      run: dotnet run
+      run: |
+        output=$(dotnet run)
+        if [ "$output" == "Hello World!" ]; then
+          echo "Test passed!"
+        else
+          echo "Test failed."
+          exit 1
+        fi
